#!/bin/bash

set -eu

# users/groups creation from qemu RPM spec
# https://apps.fedoraproject.org/packages/qemu/sources/spec/
getent group kvm >/dev/null || groupadd -g 36 -r kvm
getent group qemu >/dev/null || groupadd -g 107 -r qemu
getent passwd qemu >/dev/null || \
  useradd -r -u 107 -g qemu -G kvm -d / -s /sbin/nologin \
    -c "qemu user" qemu
# https://apps.fedoraproject.org/packages/libvirt/sources/spec/
getent group libvirt >/dev/null || groupadd -r libvirt

[ -e /usr/lib/passwd ] && USR_LIB_PASSWD="-v /usr/lib/passwd:/usr/lib/passwd:ro" || USR_LIB_PASSWD=""
[ -e /usr/lib/group ] && USR_LIB_GROUP="-v /usr/lib/group:/usr/lib/group:ro" || USR_LIB_GROUP=""

mkdir -p /etc/libvirt
mkdir -p /run/libvirt
mkdir -p /var/lib/libvirt

podman run \
    -d \
    --name mugful_libvirtd \
    --log-driver journald \
    --conmon-pidfile /run/mugful_libvirtd.pid \
    --privileged \
    --pid=host \
    --net=host \
    --security-opt label=disable \
    $USR_LIB_GROUP \
    $USR_LIB_PASSWD \
    -v /dev/kvm:/dev/kvm:rw \
    -v /dev/net:/dev/net:rw \
    -v /etc/group:/etc/group:ro \
    -v /etc/libvirt:/etc/libvirt:z \
    -v /etc/nsswitch.conf:/etc/nsswitch.conf:ro \
    -v /etc/passwd:/etc/passwd:ro \
    -v /lib/modules:/lib/modules:ro \
    -v /run/dbus:/run/dbus:shared \
    -v /run/libvirt:/run/libvirt:shared,z \
    -v /sys/fs/cgroup:/sys/fs/cgroup \
    -v /var/lib/libvirt:/var/lib/libvirt:shared,z \
    quay.io/mugful/fedora-libvirt container_libvirtd "$@"
